# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [AMVETS, fortnight]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username opensea.io
ko_fi: # Replace with a single Ko-fi username mouse3687
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username Alexk35
issuehunt: # Replace with a single IssueHunt username Emma12
otechie: # Replace with a single Otechie username Cesar1587
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://soundcloud.com/soundcloud-hustle/sets/late-nite-hip-hop-party-pourin?ref=clipboard&p=i&c=0','https://open.spotify.com/playlist/37i9dQZF1E35KtsaJ5ndhc?si=BR6rrj0jQ5-3lNlWhUdmPA','https://www.wix.com/blog/2019/06/psychology-of-selling','https://services.google.com/fh/files/misc/gc_consulting_cloud_sprint_sap.pdf','https://www.bbc.com/news/world-latin-america-55670786?ns_mchannel=social&ns_source=twitter&ns_campaign=bbc_live&ns_linkname=55670786%26Young%2C%20black%20and%20more%20likely%20to%20die%262021-01-15T00%3A04%3A22.353Z&ns_fee=0&pinned_post_locator=urn:bbc:cps:curie:asset:0e8573f7-ebba-4aea-aff7-247895579bc6&pinned_post_asset_id=55670786&pinned_post_type=share','https://current.com','https://legal.thomsonreuters.com/en/insights/articles/how-to-take-on-the-challenges-of-fintech']
